"use client";

import React, { useState, useEffect, useRef } from 'react';
import MainLayout from '@/components/layout/MainLayout';
import { 
  FileText, Download, Calendar, Clock, MoreVertical, Plus, Search,
  Filter, CheckCircle2, RefreshCw, FileBarChart, Sparkles, Zap, 
  BarChart3, PieChart, LineChart as LineChartIcon, Maximize2, Layers,
  TrendingUp, AlertCircle, Cpu, Send, Paperclip, ChevronRight, Save,
  Trash2, FileSpreadsheet, ExternalLink, X, ArrowLeft
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { analyticsApi } from '@/lib/api';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, 
  LineChart, Line, PieChart as RePieChart, Pie, Cell, AreaChart, Area, Legend
} from 'recharts';

// --- VISUALIZATION COMPONENTS ---

const COLORS = ['#4c4ceb', '#7373f0', '#38bdf8', '#818cf8', '#6366f1'];

const SmartVisualization = ({ data, type, title, onMaximize }: { data: any[], type: string, title?: string, onMaximize?: () => void }) => {
  if (!data || data.length === 0) return null;
  return (
    <motion.div 
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="w-full h-[400px] mb-10 p-8 bg-white dark:bg-slate-900 rounded-[40px] border border-slate-100 dark:border-white/5 shadow-2xl overflow-hidden group relative"
    >
      <div className="flex items-center justify-between mb-8">
         <div className="flex items-center gap-4">
            <div className="p-3 bg-primary text-white rounded-2xl shadow-lg shadow-primary/20">
               {type === 'bar' && <BarChart3 size={20} />}
               {type === 'line' && <LineChartIcon size={20} />}
               {type === 'pie' && <PieChart size={20} />}
               {type === 'area' && <Layers size={20} />}
            </div>
            <div>
               <h3 className="text-lg font-bold text-slate-900 dark:text-white leading-none">{title || 'Neural Insight View'}</h3>
               <p className="text-xs text-slate-400 mt-1 uppercase tracking-widest font-bold">Generated by MYRIOX</p>
            </div>
         </div>
         <div className="flex gap-2">
            <button className="p-2.5 bg-slate-50 dark:bg-white/5 rounded-xl text-slate-400 hover:text-primary transition-all"><Download size={16} /></button>
            <button 
              onClick={onMaximize}
              className="p-2.5 bg-primary/10 text-primary rounded-xl hover:bg-primary hover:text-white transition-all shadow-lg active:scale-95"
            >
              <Maximize2 size={16} />
            </button>
         </div>
      </div>
      
      <ResponsiveContainer width="100%" height="70%">
        {type === 'bar' ? (
          <BarChart data={data}>
            <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#8884d822" />
            <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fontSize: 10, fill: '#64748b', fontWeight: 'bold'}} />
            <YAxis axisLine={false} tickLine={false} tick={{fontSize: 10, fill: '#64748b', fontWeight: 'bold'}} />
            <Tooltip contentStyle={{ borderRadius: '24px', border: 'none', boxShadow: '0 20px 40px rgba(0,0,0,0.2)', backgroundColor: '#0f172a', color: '#fff' }} />
            <Bar dataKey="value" fill="#4c4ceb" radius={[10, 10, 0, 0]} barSize={50} />
          </BarChart>
        ) : type === 'line' ? (
          <LineChart data={data}>
            <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#8884d822" />
            <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fontSize: 10, fill: '#64748b', fontWeight: 'bold'}} />
            <YAxis axisLine={false} tickLine={false} tick={{fontSize: 10, fill: '#64748b', fontWeight: 'bold'}} />
            <Tooltip contentStyle={{ borderRadius: '24px', border: 'none', boxShadow: '0 20px 40px rgba(0,0,0,0.2)', backgroundColor: '#0f172a' }} />
            <Line type="monotone" dataKey="value" stroke="#4c4ceb" strokeWidth={5} dot={{ r: 6, fill: '#4c4ceb', strokeWidth: 3, stroke: '#fff' }} activeDot={{ r: 8 }} />
          </LineChart>
        ) : type === 'area' ? (
          <AreaChart data={data}>
            <defs>
              <linearGradient id="colorArea" x1="0" y1="0" x2="0" y2="1">
                <stop offset="5%" stopColor="#4c4ceb" stopOpacity={0.4}/>
                <stop offset="95%" stopColor="#4c4ceb" stopOpacity={0}/>
              </linearGradient>
            </defs>
            <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#8884d822" />
            <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fontSize: 10, fill: '#64748b', fontWeight: 'bold'}} />
            <YAxis axisLine={false} tickLine={false} tick={{fontSize: 10, fill: '#64748b', fontWeight: 'bold'}} />
            <Tooltip contentStyle={{ borderRadius: '24px', border: 'none', boxShadow: '0 20px 40px rgba(0,0,0,0.2)', backgroundColor: '#0f172a' }} />
            <Area type="monotone" dataKey="value" stroke="#4c4ceb" fillOpacity={1} fill="url(#colorArea)" strokeWidth={5} />
          </AreaChart>
        ) : (
          <RePieChart>
            <Pie data={data} innerRadius={80} outerRadius={110} paddingAngle={8} dataKey="value">
              {data.map((entry, index) => <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />)}
            </Pie>
            <Tooltip />
            <Legend verticalAlign="bottom" align="center" />
          </RePieChart>
        )}
      </ResponsiveContainer>
    </motion.div>
  );
};

// --- MAIN PAGE ---

export default function ReportsPage() {
  const [activeTab, setActiveTab] = useState<'builder' | 'archive'>('builder');
  const [query, setQuery] = useState('');
  const [isSynthesizing, setIsSynthesizing] = useState(false);
  const [reportElements, setReportElements] = useState<any[]>([]);
  const [showSaveToast, setShowSaveToast] = useState(false);
  const [maximizedChart, setMaximizedChart] = useState<any>(null);
  const [viewingSavedReport, setViewingSavedReport] = useState<any>(null);
  
  const [archivedReports, setArchivedReports] = useState<any[]>([
    { id: 1, name: "Q4 Market Analysis Trends", date: "2023-11-15", status: "Stored", type: "Predictive", size: "2.4 MB", elements: [{type: 'text', content: 'Sample data from last analysis.'}] },
    { id: 2, name: "Customer Churn Risk", date: "2023-11-12", status: "Stored", type: "Analytical", size: "1.1 MB", elements: [] },
    { id: 3, name: "Revenue Growth Projections", date: "2023-11-10", status: "Stored", type: "Financial", size: "3.8 MB", elements: [] }
  ]);
  const chatEndRef = useRef<HTMLDivElement>(null);

  const handleSynthesize = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!query.trim()) return;

    const userPrompt = query;
    setQuery('');
    setReportElements(prev => [...prev, { type: 'prompt', content: userPrompt }]);
    setIsSynthesizing(true);

    try {
      const response = await analyticsApi.chatWithData(userPrompt, 1);
      const content = response.response;
      
      const chartRegex = /```chart-data\n([\s\S]*?)\n```/;
      const match = content.match(chartRegex);
      
      if (match) {
        try {
          const chartConfig = JSON.parse(match[1]);
          setReportElements(prev => [...prev, { 
            type: 'chart', 
            chartType: chartConfig.type, 
            data: chartConfig.data, 
            title: chartConfig.title 
          }]);
        } catch (e) {
          setReportElements(prev => [...prev, { type: 'text', content: content }]);
        }
      } else {
        setReportElements(prev => [...prev, { type: 'text', content: content }]);
      }
    } catch (err) {
      setReportElements(prev => [...prev, { type: 'text', content: "Neural synthesis failed. Check connection." }]);
    } finally {
      setIsSynthesizing(false);
    }
  };

  const handleSaveReport = () => {
    if (reportElements.length === 0) return;
    
    const newReport = {
      id: Date.now(),
      name: reportElements.find(el => el.type === 'prompt')?.content?.slice(0, 30) || "AI Custom Report",
      date: new Date().toISOString().split('T')[0],
      status: "Stored",
      type: "AI Insight",
      size: (Math.random() * 5).toFixed(1) + " MB",
      elements: [...reportElements] // Core part: save the elements
    };

    setArchivedReports(prev => [newReport, ...prev]);
    
    setShowSaveToast(true);
    setTimeout(() => setShowSaveToast(false), 3000);
  };

  const deleteReport = (id: number) => {
    if (confirm("Are you sure you want to delete this report?")) {
      setArchivedReports(prev => prev.filter(r => r.id !== id));
      if (viewingSavedReport?.id === id) setViewingSavedReport(null);
    }
  };

  const downloadCSV = (report: any) => {
    const csvContent = "data:text/csv;charset=utf-8,Report Name,Date,Type,Size\n" 
      + `${report.name},${report.date},${report.type},${report.size}`;
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `${report.name}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [reportElements, isSynthesizing]);

  return (
    <MainLayout>
      <div className="flex flex-col h-[calc(100vh-100px)] relative">
         
         {/* Top Level Toast Notification */}
         <AnimatePresence>
            {showSaveToast && (
              <motion.div 
                initial={{ opacity: 0, x: 100 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: 100 }}
                className="fixed top-24 right-12 z-[100] bg-emerald-500 text-white px-8 py-4 rounded-[24px] shadow-2xl flex items-center gap-4"
              >
                 <CheckCircle2 size={24} />
                 <div><h4 className="font-bold">Neural Sync Complete</h4><p className="text-xs opacity-80">Report added to Archive</p></div>
              </motion.div>
            )}
         </AnimatePresence>

         {/* Full Screen Chart Modal */}
         <AnimatePresence>
            {maximizedChart && (
              <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-[150] bg-slate-950/90 backdrop-blur-2xl flex items-center justify-center p-12">
                 <motion.div initial={{ scale: 0.9 }} animate={{ scale: 1 }} className="w-full max-w-6xl aspect-[16/9] bg-white dark:bg-slate-900 rounded-[60px] p-16 shadow-2xl relative border border-white/10">
                    <button onClick={() => setMaximizedChart(null)} className="absolute top-10 right-10 size-14 bg-slate-100 dark:bg-white/10 rounded-2xl flex items-center justify-center hover:bg-red-500 hover:text-white transition-all"><X size={28} /></button>
                    <div className="flex items-center gap-6 mb-12"><div className="p-5 bg-primary text-white rounded-3xl">{maximizedChart.type === 'bar' && <BarChart3 size={40} />}{maximizedChart.type === 'line' && <LineChartIcon size={40} />}{maximizedChart.type === 'pie' && <PieChart size={40} />}{maximizedChart.type === 'area' && <Layers size={40} />}</div><div><h2 className="text-4xl font-black dark:text-white">{maximizedChart.title}</h2><p className="text-slate-400 font-bold uppercase tracking-[0.3em] mt-2 text-sm">Full Spectrum Neural Engine Analysis</p></div></div>
                    <div className="w-full h-[70%]"><ResponsiveContainer width="100%" height="100%">{maximizedChart.type === 'bar' ? (<BarChart data={maximizedChart.data}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#8884d822" /><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fontSize: 14, fill: '#64748b', fontWeight: 'bold'}} /><YAxis axisLine={false} tickLine={false} tick={{fontSize: 14, fill: '#64748b', fontWeight: 'bold'}} /><Tooltip contentStyle={{ borderRadius: '32px', border: 'none', boxShadow: '0 30px 60px rgba(0,0,0,0.3)', backgroundColor: '#0f172a' }} /><Bar dataKey="value" fill="#4c4ceb" radius={[16, 16, 0, 0]} barSize={80} /></BarChart>) : maximizedChart.type === 'line' ? (<LineChart data={maximizedChart.data}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#8884d822" /><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fontSize: 14, fill: '#64748b', fontWeight: 'bold'}} /><YAxis axisLine={false} tickLine={false} tick={{fontSize: 14, fill: '#64748b', fontWeight: 'bold'}} /><Tooltip contentStyle={{ borderRadius: '32px', border: 'none', boxShadow: '0 30px 60px rgba(0,0,0,0.3)', backgroundColor: '#0f172a' }} /><Line type="monotone" dataKey="value" stroke="#4c4ceb" strokeWidth={8} dot={{ r: 10, fill: '#4c4ceb', strokeWidth: 5, stroke: '#fff' }} activeDot={{ r: 14 }} /></LineChart>) : maximizedChart.type === 'area' ? (<AreaChart data={maximizedChart.data}><defs><linearGradient id="colorAreaMax" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#4c4ceb" stopOpacity={0.6}/><stop offset="95%" stopColor="#4c4ceb" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#8884d822" /><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fontSize: 14, fill: '#64748b', fontWeight: 'bold'}} /><YAxis axisLine={false} tickLine={false} tick={{fontSize: 14, fill: '#64748b', fontWeight: 'bold'}} /><Tooltip contentStyle={{ borderRadius: '32px', border: 'none', boxShadow: '0 30px 60px rgba(0,0,0,0.3)', backgroundColor: '#0f172a' }} /><Area type="monotone" dataKey="value" stroke="#4c4ceb" fillOpacity={1} fill="url(#colorAreaMax)" strokeWidth={8} /></AreaChart>) : (<RePieChart><Pie data={maximizedChart.data} innerRadius={140} outerRadius={200} paddingAngle={12} dataKey="value" animationDuration={1500}>{maximizedChart.data.map((entry: any, index: number) => <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />)}</Pie><Tooltip /><Legend verticalAlign="bottom" align="center" iconSize={20} wrapperStyle={{paddingTop: '40px'}} /></RePieChart>)}</ResponsiveContainer></div>
                 </motion.div>
              </motion.div>
            )}
         </AnimatePresence>

         {/* Top Header/Tab Bar */}
         <div className="flex items-center justify-between mb-8">
            <div className="flex items-center gap-6">
               <button onClick={() => { setActiveTab('builder'); setViewingSavedReport(null); }} className={cn("px-6 py-3 rounded-2xl font-bold text-sm transition-all flex items-center gap-2", activeTab === 'builder' ? "bg-primary text-white shadow-xl shadow-primary/20 scale-105" : "text-slate-400 hover:text-slate-600 dark:hover:text-white")}><Sparkles size={18} /> AI Report Builder</button>
               <button onClick={() => setActiveTab('archive')} className={cn("px-6 py-3 rounded-2xl font-bold text-sm transition-all flex items-center gap-2", activeTab === 'archive' ? "bg-primary text-white shadow-xl shadow-primary/20 scale-105" : "text-slate-400 hover:text-slate-600 dark:hover:text-white")}><FileBarChart size={18} /> Archive</button>
            </div>
            
            <div className="flex items-center gap-4">
               {activeTab === 'builder' && (
                 <button onClick={handleSaveReport} className="flex items-center gap-2 px-6 py-3 bg-white dark:bg-slate-900 border border-slate-200 dark:border-white/5 rounded-2xl text-sm font-bold shadow-sm hover:bg-slate-50 transition-all text-slate-700 dark:text-slate-300"><Save size={18} /> Save Workspace</button>
               )}
               <button className="flex items-center gap-2 px-6 py-3 bg-emerald-500 text-white rounded-2xl text-sm font-bold shadow-xl shadow-emerald-500/20 hover:scale-105 transition-all"><Download size={18} /> Export PDF</button>
            </div>
         </div>

         {activeTab === 'builder' ? (
           <div className="flex-1 flex overflow-hidden bg-slate-50/50 dark:bg-background-dark/20 rounded-[48px] border border-slate-100 dark:border-primary/5 shadow-inner">
              {/* Sidebar Left */}
              <div className="w-96 border-r border-slate-100 dark:border-white/5 flex flex-col p-8 bg-white dark:bg-[#0c0c18]">
                 <div className="mb-10"><div className="flex items-center gap-3 text-primary mb-4"><Zap size={24} className="fill-primary" /><h3 className="text-xl font-extrabold uppercase tracking-tight">AI Composer</h3></div><p className="text-xs text-slate-400 font-bold leading-relaxed">Tell MYRIOX what to synthesize into your report. Ask for charts, summaries, or predictive data.</p></div>
                 <div className="flex-1 overflow-y-auto space-y-6 no-scrollbar pb-10">
                    <SuggestionButton text="Analyse monthly growth" onClick={() => setQuery("Visualise my monthly revenue growth for the last 6 months as an Area Chart")} />
                    <SuggestionButton text="Customer distribution" onClick={() => setQuery("Show customer distribution by age group in a Pie Chart")} />
                    <SuggestionButton text="Detect anomalies" onClick={() => setQuery("Scan current datasets for anomalies and show them in a Bar Chart")} />
                    <SuggestionButton text="Predict future churn" onClick={() => setQuery("Perform a churn prediction for next quarter and show result in a Line Chart")} />
                 </div>
                 <form onSubmit={handleSynthesize} className="relative group">
                    <textarea className="w-full bg-slate-50 dark:bg-slate-900/50 border border-slate-200 dark:border-primary/10 rounded-3xl p-6 text-sm outline-none focus:ring-4 focus:ring-primary/5 transition-all min-h-[160px] resize-none dark:text-white" placeholder="Describe report step..." value={query} onChange={e => setQuery(e.target.value)} />
                    <button type="submit" disabled={isSynthesizing || !query.trim()} className="absolute bottom-4 right-4 size-12 bg-primary text-white rounded-2xl flex items-center justify-center hover:scale-110 active:scale-95 transition-all shadow-xl shadow-primary/30 disabled:opacity-50">{isSynthesizing ? <RefreshCw size={20} className="animate-spin" /> : <Send size={20} />}</button>
                 </form>
              </div>

              {/* Main Canvas Right */}
              <div className="flex-1 overflow-y-auto p-12 no-scrollbar scroll-smooth">
                 <div className="max-w-4xl mx-auto">
                    <div className="text-center mb-16"><h2 className="text-4xl font-extrabold text-slate-900 dark:text-white mb-4">Live Analysis Canvas</h2><div className="flex items-center justify-center gap-4 text-xs font-extrabold uppercase tracking-[0.3em] text-slate-400">Neural Link Stable <div className="size-2 bg-emerald-500 rounded-full animate-pulse" /> Workspace 4.0</div></div>
                    <div className="space-y-12 pb-40">
                       {reportElements.map((el, i) => (
                          <div key={i}>
                             {el.type === 'prompt' && <div className="flex items-center gap-4 mb-4"><div className="h-px flex-1 bg-slate-100 dark:bg-white/5" /><span className="text-[10px] font-extrabold text-primary uppercase tracking-widest bg-primary/10 px-4 py-1 rounded-full">{el.content}</span><div className="h-px flex-1 bg-slate-100 dark:bg-white/5" /></div>}
                             {el.type === 'chart' && <SmartVisualization type={el.chartType} data={el.data} title={el.title} onMaximize={() => setMaximizedChart({ type: el.chartType, data: el.data, title: el.title })} />}
                             {el.type === 'text' && <div className="bg-white dark:bg-slate-900/50 p-8 rounded-[40px] border border-slate-100 dark:border-white/5 text-sm leading-relaxed text-slate-600 dark:text-slate-300 shadow-sm">{el.content}</div>}
                          </div>
                       ))}
                       {isSynthesizing && <div className="flex flex-col items-center gap-6 py-20 opacity-50 animate-pulse"><Cpu size={48} className="text-primary animate-spin-slow" /><div className="text-sm font-bold uppercase tracking-widest text-primary">Synthesizing Neural Report...</div></div>}
                       {reportElements.length === 0 && <div className="flex flex-col items-center justify-center py-40 opacity-20"><Layers size={100} className="mb-6 text-slate-400" /><h3 className="text-xl font-bold">Empty Canvas</h3><p className="text-sm mt-2">Instruction the AI agent to start building your report.</p></div>}
                       <div ref={chatEndRef} />
                    </div>
                 </div>
              </div>
           </div>
         ) : (
           <div className="flex-1 flex flex-col relative overflow-hidden bg-white dark:bg-slate-950 rounded-[48px] border border-slate-200 dark:border-white/5 shadow-2xl">
              {viewingSavedReport ? (
                 <motion.div initial={{ opacity: 0, scale: 0.98 }} animate={{ opacity: 1, scale: 1 }} className="flex-1 flex flex-col p-12 overflow-y-auto no-scrollbar">
                    <div className="max-w-4xl mx-auto w-full">
                       <button onClick={() => setViewingSavedReport(null)} className="flex items-center gap-2 text-primary font-bold text-sm mb-10 hover:translate-x-[-4px] transition-transform">
                          <ArrowLeft size={18} /> Back to Archive
                       </button>
                       <div className="flex items-center justify-between mb-16">
                          <div>
                             <h2 className="text-4xl font-extrabold dark:text-white capitalize">{viewingSavedReport.name}</h2>
                             <p className="text-slate-400 font-bold uppercase tracking-widest mt-2">{viewingSavedReport.date} • {viewingSavedReport.type}</p>
                          </div>
                          <div className="flex gap-4">
                             <button onClick={() => downloadCSV(viewingSavedReport)} className="p-4 bg-emerald-500/10 text-emerald-600 rounded-3xl hover:bg-emerald-500 hover:text-white transition-all"><Download size={24} /></button>
                             <button onClick={() => deleteReport(viewingSavedReport.id)} className="p-4 bg-red-500/10 text-red-500 rounded-3xl hover:bg-red-500 hover:text-white transition-all"><Trash2 size={24} /></button>
                          </div>
                       </div>
                       <div className="space-y-12 pb-20">
                          {viewingSavedReport.elements.length > 0 ? viewingSavedReport.elements.map((el: any, i: number) => (
                             <div key={i}>
                                {el.type === 'prompt' && <div className="flex items-center gap-4 mb-4"><div className="h-px flex-1 bg-slate-100 dark:bg-white/5" /><span className="text-[10px] font-extrabold text-primary uppercase tracking-widest bg-primary/10 px-4 py-1 rounded-full">{el.content}</span><div className="h-px flex-1 bg-slate-100 dark:bg-white/5" /></div>}
                                {el.type === 'chart' && <SmartVisualization type={el.chartType} data={el.data} title={el.title} onMaximize={() => setMaximizedChart({ type: el.chartType, data: el.data, title: el.title })} />}
                                {el.type === 'text' && <div className="bg-slate-50 dark:bg-slate-900 p-10 rounded-[40px] border border-slate-100 dark:border-white/5 text-sm leading-relaxed dark:text-slate-300 shadow-sm">{el.content}</div>}
                             </div>
                          )) : (
                             <div className="text-center py-20 opacity-30"><AlertCircle size={48} className="mx-auto mb-4" /><p>No data elements stored for this report.</p></div>
                          )}
                       </div>
                    </div>
                 </motion.div>
              ) : (
                 <ReportsArchive items={archivedReports} onDelete={deleteReport} onDownload={downloadCSV} onView={(r: any) => setViewingSavedReport(r)} />
              )}
           </div>
         )}
      </div>

      <style jsx global>{`
        .no-scrollbar::-webkit-scrollbar { display: none; }
        .animate-spin-slow { animation: spin 3s linear infinite; }
        @keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }
      `}</style>
    </MainLayout>
  );
}

const SuggestionButton = ({ text, onClick }: { text: string, onClick: () => void }) => (
  <button onClick={onClick} className="w-full text-left p-4 rounded-2xl border border-slate-100 dark:border-white/5 hover:border-primary/50 hover:bg-primary/5 transition-all group flex items-center justify-between"><span className="text-xs font-bold text-slate-500 group-hover:text-primary transition-colors">{text}</span><ChevronRight size={14} className="text-slate-300 group-hover:text-primary transition-transform group-hover:translate-x-1" /></button>
);

const ReportsArchive = ({ items, onDelete, onDownload, onView }: any) => {
  if (items.length === 0) return <div className="flex-1 flex flex-col items-center justify-center p-20 text-center opacity-40"><FileBarChart size={80} className="mb-8 text-slate-400" /><h2 className="text-2xl font-bold">No Archived Reports</h2><p className="text-sm mt-3 max-w-xs">Reports saved from the builder will appear here.</p></div>;
  return (
    <div className="p-12 overflow-y-auto no-scrollbar">
       <div className="flex items-center justify-between mb-12 px-4"><div className="flex items-center gap-4"><div className="p-4 bg-primary/10 rounded-2xl text-primary"><FileBarChart size={28} /></div><h2 className="text-3xl font-black dark:text-white">Neural Archive</h2></div><p className="text-sm font-black text-slate-400 uppercase tracking-widest">{items.length} Reports Found</p></div>
       <table className="w-full text-left border-separate border-spacing-y-4">
          <thead><tr className="text-[10px] font-bold text-slate-400 uppercase tracking-[0.2em] px-8"><th className="px-10 pb-4">Report Details</th><th className="px-10 pb-4 text-center">Inference Date</th><th className="px-10 pb-4 text-center">Insight Type</th><th className="px-10 pb-4 text-center">Payload Size</th><th className="px-10 pb-4 text-right pr-12">Neural Actions</th></tr></thead>
          <tbody>
             {items.map((report: any) => (
                <tr key={report.id} className="group bg-slate-50/50 dark:bg-white/5 hover:bg-slate-100 dark:hover:bg-primary/10 transition-all cursor-pointer" onClick={() => onView(report)}>
                   <td className="px-10 py-6 first:rounded-l-[32px] border-y border-l border-transparent group-hover:border-primary/20"><div className="flex items-center gap-5"><div className="size-14 rounded-2xl bg-white dark:bg-slate-800 shadow-lg flex items-center justify-center text-primary group-hover:scale-110 transition-transform"><FileText size={26} /></div><div><p className="text-base font-bold text-slate-900 dark:text-white">{report.name}</p><p className="text-[10px] text-slate-400 mt-1 font-bold uppercase tracking-widest">Encrypted Data Stream</p></div></div></td>
                   <td className="px-10 py-6 text-center border-y border-transparent group-hover:border-primary/20"><p className="text-xs font-bold text-slate-700 dark:text-slate-300">{report.date}</p></td>
                   <td className="px-10 py-6 text-center border-y border-transparent group-hover:border-primary/20"><span className="px-4 py-1.5 bg-primary/10 text-primary rounded-xl text-[10px] font-black uppercase border border-primary/10">{report.type}</span></td>
                   <td className="px-10 py-6 text-center border-y border-transparent group-hover:border-primary/20"><p className="text-xs font-black text-primary/60">{report.size}</p></td>
                   <td className="px-10 py-6 text-right last:rounded-r-[32px] pr-12 border-y border-r border-transparent group-hover:border-primary/20">
                      <div className="flex items-center justify-end gap-3 opacity-0 group-hover:opacity-100 transition-all">
                         <button onClick={(e) => { e.stopPropagation(); onDownload(report); }} className="p-3 bg-emerald-500/10 text-emerald-600 rounded-2xl hover:bg-emerald-500 hover:text-white transition-all"><FileSpreadsheet size={20} /></button>
                         <button onClick={(e) => { e.stopPropagation(); onView(report); }} className="p-3 bg-primary/10 text-primary rounded-2xl hover:bg-primary hover:text-white transition-all"><ExternalLink size={20} /></button>
                         <button onClick={(e) => { e.stopPropagation(); onDelete(report.id); }} className="p-3 bg-red-500/10 text-red-500 rounded-2xl hover:bg-red-500 hover:text-white transition-all"><Trash2 size={20} /></button>
                      </div>
                   </td>
                </tr>
             ))}
          </tbody>
       </table>
    </div>
  );
};
